# Generated by Django 4.1.3 on 2023-01-21 17:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=5)),
                ("sign", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cryptocurrencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField(default=0.0)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cash",
                        to="manager.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cash",
                "verbose_name_plural": "cash",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("balance", models.FloatField(default=0.0)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cards",
                        to="manager.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bank_name"],
            },
        ),
        migrations.CreateModel(
            name="Accountancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IO",
                    models.CharField(
                        choices=[("I", "Income"), ("O", "Outcome")],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("IO_type", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountancy",
                        to="manager.card",
                    ),
                ),
                (
                    "cash",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountancy",
                        to="manager.cash",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountancy",
                        to="manager.cryptocurrency",
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="cryptocurrency",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_cryptocurrencies"
            ),
        ),
        migrations.AddConstraint(
            model_name="cryptocurrency",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)),
                name="positive_cryptocurrency_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="cash",
            constraint=models.UniqueConstraint(
                fields=("user", "currency"), name="unique_user_cash"
            ),
        ),
        migrations.AddConstraint(
            model_name="cash",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="positive_cash_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("user", "bank_name", "type"), name="unique_user_cards"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="positive_card_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountancy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("card__isnull", False),
                        ("cash__isnull", True),
                        ("cryptocurrency__isnull", True),
                    ),
                    models.Q(
                        ("card__isnull", True),
                        ("cash__isnull", False),
                        ("cryptocurrency__isnull", True),
                    ),
                    models.Q(
                        ("card__isnull", True),
                        ("cash__isnull", True),
                        ("cryptocurrency__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_one_wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountancy",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)), name="positive_amount"
            ),
        ),
    ]
